# SonarCloud Configuration
# https://docs.sonarcloud.io/advanced-setup/analysis-parameters/

sonar.projectKey=osodevops_akka-openapi-maven-plugin
sonar.organization=osodevops
sonar.projectName=Akka OpenAPI Maven Plugin

# Source code
sonar.sources=akka-openapi-annotations/src/main/java,akka-openapi-core/src/main/java,akka-openapi-maven-plugin/src/main/java
sonar.tests=akka-openapi-annotations/src/test/java,akka-openapi-core/src/test/java,akka-openapi-maven-plugin/src/test/java
sonar.java.binaries=**/target/classes
sonar.java.source=17

# Coverage
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml

# Exclusions
sonar.exclusions=**/target/**,akka-openapi-example/**

# Encoding
sonar.sourceEncoding=UTF-8
